### ISSUE TITLE
PluginException with IntelliJ IDEA 2024.2.0.1

### ISSUE THREAD

**Issue by ofry** [bitjerry/Headers#3]
### What happened?

Plugin Headers 2.0.3 had crashed.

### Relevant log output or stack trace

```shell
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'su.gov.headers.actions.CookieAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: su.gov.Header]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

### Steps to reproduce

```
IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024

Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-40-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 10240M
Cores: 8
Registry:
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.20224.385)
  com.intellij.classic.ui (242.20224.159)
  de.espend.idea.localization (0.0.6)
  Batch Scripts Support (1.0.13)
  icu.windea.bbcode (1.8)
  com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
  dev.meanmail.plugin.nginx-intellij-plugin-pro (2024.3)
  intellij-awk (0.4.5)
  Shell Process (1.3.2)
  com.plugin.image-icon-viewer (1.0.11)
  com.github.obiscr.exceleditor (2024.8.1-222.242)
  de.dieploegers.develop.idea.shellfilter (5.0.1)
  org.intellij.RegexpTester (2.2.0)
  ru.limydesign.plugins.yandex.translate (0.1.0)
  artsiomch.cmake (242.0.1-EAP)
  artsiomch.cmake.plus (242.0.1-EAP)
  ru.ilimurzin.bitrixexcluder (2.0.0)
  com.github.izhangzhihao.intellijgooglesearch (0.0.2)
  com.github.exidcuter.dockerregistryexplorer (1.1.0-stable)
  PythonCore (242.20224.300)
  com.jetbrains.CyanTheme (1.3)
  com.intellij.apacheConfig (242.20224.385)
  com.github.warningimhack3r.npmupdatedependencies (3.0.0)
  com.ess.terminal-pro (1.1.9.241)
  org.jetbrains.plugins.stylus (242.20224.155)
  com.remoterapp.adbremote.jsonviewer.id (0.1.1)
  com.jetbrains.space (242.20224.155)
  com.jetbrains.hackathon.indices.viewer (1.28)
  com.mroche.JsonHelper (1.3.2)
  de.ehmkah.projects.imgdiff (1.11.0)
  String Manipulation (9.14.1)
  org.jetbrains.plugins.localization (242.20224.159)
  su.gov.Header (2.0.3)
  com.devwook.copy_path_helper (1.1.2)
  lermitage.intellij.extra.icons (2024.6.4)
  krasa.IdeaIconPack (1.14)
  Pythonid (242.20224.387)
  com.intellij.python.django (242.20224.159)
  ru.meanmail.plugin.pyannotations (2022.2)
  io.github.guoci.PythonDocumentationLinkProvider (0.1.5)
  org.tonybaloney.security.pycharm-security (1.29.0)
  ru.meanmail.plugins.prettify-python (2022.1)
  ru.meanmail.plugin.django_command_runner (2022.1)
  GrepConsole (13.1.0-IJ2023.3)
  man-page-viewer (0.1.1)
  MHCommitMessageTemplate (1.0.3)
  com.intellij.ml.llm (242.20224.393)
  com.majera.intellij.codereview.bitbucket (2024.2.4.242)
  git-extended-update-index (0.1.3)
  mobi.hsz.idea.gitignore (4.5.3)
  com.jetbrains.packagesearch.intellij-plugin (242.0.12)
  com.intellij.tide (242.20224.393)
  com.rxliuli.vite-jetbrains-plugin (0.2.2)
  com.github.kawamataryo.copygithublink (0.5.3)
  com.majera.intellij.codereview.gitlab (2024.2.4.242)
  com.jetbrains.php (242.20224.387)
  com.jetbrains.php.joomla (242.20224.159)
  com.jetbrains.twig (242.20224.385)
  com.funivan.idea.phpClean (2023.12.17)
  com.clutcher.comments_highlighter (2024.1.34)
  nl.deschepers.laraveltinker (2.7.3)
  ru.itrack.bitrix (0.2.0)
  com.kalessil.phpStorm.phpInspectionsUltimate-mp (2024.1.1)
  com.jetbrains.php.blade (242.20224.387)
  dev.ekvedaras.laravelquery (4.0.4)
  com.kalessil.phpStorm.yii2inspections (1.0.6)
  org.jetbrains.plugins.phpstorm-remote-interpreter (242.20224.159)
  org.jetbrains.plugins.phpstorm-docker (242.20224.159)
  com.jetbrains.php.framework (242.20224.385)
  com.jetbrains.php.wordPress (242.20224.387)
  ru.vkurdin.idea.php.lambdafolding (0.3.0)
  org.exbin.deltahex.intellij (0.2.10.1)
  com.intellij.php.codeigniter3 (0.6.0)
  com.github.woru.options-completion-phpstorm-plugin (0.0.7)
  ru.adelf.idea.dotenv (2024.2.1)
  com.laravel_idea.plugin (8.2.4.242)
  com.eny.i18n (2.6.2)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.0.2)
  fr.adrienbrault.idea.symfony2plugin (2024.1.275)
  de.espend.idea.shopware (5.0.0)
  de.espend.idea.php.drupal (0.6.0)
  org.endpointdeps.EndpointDependencies (1.3)
  zielu.gittoolbox (500.2.14+242)
Kotlin: 242.20224.387-IJ
Current Desktop: KDE
```

Headers 2.0.3

### Gradle IntelliJ Plugin version

242.20224.387

### Operating System

KUbuntu 24.04 x64

**Comment by bitjerry** [comment]
New version 2.0.4 has been released, compatible with 2024.2, you can try it.

**Comment by ofry** [comment]
@bitjerry Will wait it in Jetbrains Marketplace.

**Comment by bitjerry** [comment]
> @bitjerry Will wait it in Jetbrains Marketplace.

The new version has been updated in Jetbrains Marketplace

**Comment by ofry** [comment]
Yeah, it working. Thanks.
